Repository tinylunark/lunark-front, pull requests merged in 2023-12, with the labels that each got.

#20 Property detail backend connection
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/core/core-routing.module.ts
  src/app/core/core.module.ts
  src/app/core/page-not-found/page-not-found.component.css
  src/app/core/page-not-found/page-not-found.component.html
  src/app/core/page-not-found/page-not-found.component.spec.ts
  src/app/core/page-not-found/page-not-found.component.ts
  src/app/http-interceptors/page-not-found.interceptor.ts
  src/app/properties/locations.ts
  src/app/properties/properties.ts
  src/app/properties/properties/properties.component.html
  src/app/properties/properties/properties.component.ts
  src/app/properties/property-detail/property-detail.component.html
  src/app/properties/property-detail/property-detail.component.ts
  src/app/properties/property.service.ts
  src/app/properties/search/search.component.ts
  src/app/shared/api/api-paths.enum.ts
  src/app/shared/models/property.model.ts
  src/env/environment.ts
Labels: feature

#25 Property search and filtering
  src/app/amenity.service.spec.ts
  src/app/amenity.service.ts
  src/app/properties/filter-dialog/filter-dialog.component.css
  src/app/properties/filter-dialog/filter-dialog.component.html
  src/app/properties/filter-dialog/filter-dialog.component.spec.ts
  src/app/properties/filter-dialog/filter-dialog.component.ts
  src/app/properties/properties-search.dto.ts
  src/app/properties/properties.module.ts
  src/app/properties/properties/properties.component.html
  src/app/properties/properties/properties.component.ts
  src/app/properties/property-detail/property-detail.component.ts
  src/app/properties/property.service.ts
  src/app/properties/search/search.component.html
  src/app/properties/search/search.component.ts
  src/app/shared/api/api-paths.enum.ts
  src/app/shared/models/amenity.model.ts
  src/app/shared/models/property.model.ts
  src/infrastructure/material/material.module.ts
Labels: feature

#33 Feature/9.6/booking reservation request
  src/app/properties/property-detail/dtos/reservation-request.dto.ts
  src/app/properties/property-detail/property-detail.component.html
  src/app/properties/property-detail/property-detail.component.ts
  src/app/reservation.service.spec.ts
  src/app/reservation.service.ts
  src/app/shared/api/api-paths.enum.ts
Labels: feature

#34 Send request to backend when creating account
  src/app/account/account.service.ts
  src/app/account/model/account.model.ts
  src/app/account/signup-dialog/signup-dialog.component.html
  src/app/account/signup-dialog/signup-dialog.component.ts
Labels: feature

#35 Email verification 1.1.2
  src/app/account/account-routing.module.ts
  src/app/account/account.module.ts
  src/app/account/account.service.ts
  src/app/account/verification/verification.component.css
  src/app/account/verification/verification.component.html
  src/app/account/verification/verification.component.spec.ts
  src/app/account/verification/verification.component.ts
  src/app/app-routing.module.ts
  src/app/http-interceptors/date.interceptor.ts
  src/app/shared/api/api-paths.enum.ts
Labels: feature

#38 feat: add properties price
  src/app/properties/properties/properties.component.html
  src/app/properties/properties/properties.component.ts
Labels: feature

#43 Average rating
  src/app/properties/property-detail/property-detail.component.html
  src/app/properties/property-detail/property-detail.component.ts
Labels: feature

#42 Restrict booking form visibility
  src/app/properties/property-detail/property-detail.component.html
Labels: bug

#44 feat: add map to property detail
  src/app/properties/property-detail/property-detail.component.html
  src/app/properties/property-management/location/location.component.ts
Labels: enhancement

#47 Profile image fetching and updating
  src/app/account/account.service.ts
  src/app/profile/basic-info/basic-info.component.html
  src/app/profile/basic-info/basic-info.component.ts
Labels: enhancement
