Repository tinylunark/lunark-front, pull requests merged in 2024-01, with the labels that each got.

#56 Prevent admins and unregistered users from accessing notifications page
  src/app/notifications/notifications-routing.module.ts
Labels: fix

#57 Make app usable after session has expired
  src/app/http-interceptors/unauthorized.interceptor.ts
Labels: fix

#62 fix: ignore reserved entries in the date range picker when booking a …
  src/app/properties/property-detail/property-detail.component.ts
  src/app/shared/models/property-availability-entry.model.ts
Labels: fix

#60 Hide accept and decline buttons for reservations that are not pending
  src/app/reservations/host-incoming-reservations/host-incoming-reservations.component.html
Labels: fix

#59 Host average rating
  src/app/account/model/account.model.ts
  src/app/host/host-page/host-page.component.html
  src/app/host/host-page/host-page.component.ts
Labels: refactor

#63 Story #9.6 - Booking reservation deletion
  src/app/reservations/reservation-list/reservation-list.component.html
  src/app/reservations/reservation-list/reservation-list.component.ts
  src/app/reservations/reservation.service.ts
Labels: feature

#64 Story #7.2 - Notifications toggle
  src/app/account/account.service.ts
  src/app/account/model/account.model.ts
  src/app/notifications/notifications-page/notifications-page.component.html
  src/app/notifications/notifications-page/notifications-page.component.ts
  src/app/notifications/notifications.module.ts
  src/app/shared/models/guest-notification-settings.model.ts
  src/app/shared/models/host-notification-settings.model.ts
  src/app/shared/models/notification-type.enum.ts
  src/app/shared/models/profile.model.ts
Labels: feature

#66 Add validations to the content of a review
  src/app/reviews/review-dialog/review-dialog.component.ts
Labels: fix

#65 Story #2.8 - Reports
  angular.json
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/reports/daily-report.model.ts
  src/app/reports/general-report.model.ts
  src/app/reports/general-report/general-report.component.css
  src/app/reports/general-report/general-report.component.html
  src/app/reports/general-report/general-report.component.spec.ts
  src/app/reports/general-report/general-report.component.ts
  src/app/reports/monthly-report.model.ts
  src/app/reports/property-report.model.ts
  src/app/reports/property-report/property-report.component.css
  src/app/reports/property-report/property-report.component.html
  src/app/reports/property-report/property-report.component.spec.ts
  src/app/reports/property-report/property-report.component.ts
  src/app/reports/report.service.spec.ts
  src/app/reports/report.service.ts
  src/app/reports/reports-routing.module.ts
  src/app/reports/reports.module.ts
  src/app/reports/reports/reports.component.css
  src/app/reports/reports/reports.component.html
  src/app/reports/reports/reports.component.spec.ts
  src/app/reports/reports/reports.component.ts
  src/app/shared/api/api-paths.enum.ts
  src/app/shared/util/number-to-month.ts
  src/infrastructure/material/material.module.ts
Labels: feature

#67 Karma uncaught reference error - global FIX
  angular.json
  src/app/http-interceptors/jwt.interceptor.spec.ts
  src/app/reservation.service.spec.ts
  tsconfig.spec.json
Labels: fix, test

#71 Fill property edit form
  src/app/properties/property-edit/property-edit.component.ts
  src/app/properties/property-management/description/description.component.ts
Labels: fix

#75 test: Account Update
  src/app/mocks/account.service.mock.ts
  src/app/mocks/profile.mock.ts
  src/app/mocks/profile.service.mock.ts
  src/app/mocks/shared.service.mock.ts
  src/app/profile/change-password/change-password.component.spec.ts
  src/app/profile/edit-profile/edit-profile.component.spec.ts
  src/app/profile/info-form/info-form.component.ts
  src/app/profile/mocks/profile.mock.ts
  src/app/profile/profile.module.ts
Labels: test

#74 Test reservation form
  src/app/account/account.service.mock.ts
  src/app/properties/property-detail/property-detail.component.spec.ts
  src/app/properties/property.service.mock.ts
  src/app/reservation.service.mock.ts
Labels: test
